import type { Metadata } from "next";
import { pretendard } from "@/styles/font";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { KakaoLinkButton } from "@/components/KakaoLinkButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} h-full min-h-screen`}>
      <body
        className={`${pretendard.className} h-full min-h-screen w-full overflow-auto text-black`}
      >
        <Navbar />
        {children}
        <KakaoLinkButton />
      </body>
    </html>
  );
}
