import type { Metadata } from "next";
import { pretendard } from "@/styles/font";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { FloatingButtonGroup } from "@/components/FloatingButtonGroup";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} `}>
      <body className={`${pretendard.className} w-full overflow-auto text-black`}>
        <Navbar />
        {children}
        <FloatingButtonGroup />
        <Footer />
      </body>
    </html>
  );
}
